import Providers from "@/components/Providers";
import "./globals.css";
import type { Metadata } from "next";
import { Raleway, Roboto } from "next/font/google";
import Example from "@/components/Header";
import { cn } from "@/lib/utils";
import Modal from "@/components/Modal";

// const raleway = Raleway({ subsets: ["latin"], variable: "--raleway" });
// const roboto = Roboto({
//   weight: ["400", "500"],
//   subsets: ["latin"],
//   variable: "--roboto",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="">
      <body>
        {/* <Modal /> */}
        {/* <span className={cn(roboto.variable, raleway.variable)}></span> */}
        {/* <Providers>
          <Example /> */}
        <div className="container">{children}</div>
        {/* </Providers> */}
      </body>
    </html>
  );
}
